### ISSUE TITLE
What does this do?

### ISSUE THREAD

**Issue by luzpaz** [dliess/FreeCADFrontPanelSimulation#1]
Please add a README at your convenience. Thanks!

**Comment by dliess** [comment]
It is a work in progress, later on it is going to help you create a simulation for front-panel design, that means you can move faders, push knobs, enlight leds and use surfaces you declare as displays.
These infos can be transmitted to a separate process , that can be a c++ or python application, that does the logic and uses freecad as the HW-Simulation.

**Comment by luzpaz** [comment]
@dliess very cool. Please keep me posted. thanks!

**Comment by dliess** [comment]
Of course, glad to hear you are interested, I will inform you when most of the basic features start to work.

**Comment by dliess** [comment]
Hello,
first working version online ...
Feel free to ask questions, because I have no documentation yet

**Comment by luzpaz** [comment]
screenshots ?

**Comment by dliess** [comment]
Good Idea, added some.

**Comment by dliess** [comment]
Glad to hear that, created a new topic on FC users showcase subforum,
posted a link to this github page there, maybe adding some pictures when it
gets approved.
Have you actually tried the draw-toy demo?
